### ISSUE TITLE
How to handle .ruby-version file between server and development 

### ISSUE THREAD

**Issue by westonganger** [fullstaq-labs/fullstaq-rbenv#4]
I have a `.ruby-version` file in my repo pointing to `2.6.3`, but on the server I only have `2.6.3-jemalloc`. This causes errors on the server when trying to run `rails console` or any ruby command. What is the recommended approach for this?

**Comment by westonganger** [comment]
Ok so I was thinking about creating a PR for this and I was going to use `.fullstaq-ruby-version` but then it dawned on me that maybe it would be better to simply provide a `.fullstaq-ruby-variant` file (or simply `.ruby-variant`) 

This `.fullstaq-ruby-variant` file would not specify a Ruby version but instead specify one of the following variants:
- `normal`
- `jemalloc`
- `malloctrim`

Then when loading the `.ruby-version` file we can simply append the appropriate `.fullstaq-ruby-variant` to the end of the string.

 What do you think?

**Comment by FooBarWidget** [comment]
Yes I am fine with that too.

**Comment by FooBarWidget** [comment]
Thanks for the contribution!
